services:
  # Monolith Service (Backend + Frontend)
  - type: web
    name: salary-prediction-app
    env: python
    plan: free
    region: oregon 
    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend && npm install && npm run build
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: "" # Empty means use the same host
      - key: RENDER
        value: true
